routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dashboard', 'Admin\DashboardController');
Route::resource('employees', 'Admin\UsersController');
Route::resource('department/positions', 'Admin\Departments\PositionsController');
Route::resource('department/roles', 'Admin\Departments\RolesController');
Route::resource('settings', 'SettingsController');

Route::resource('imports', 'Imported\AllProductsController');
Route::match(['get','post'], 'imports'. 'Imported\AllProductsController@updateProductName')->name('imports.updateProductName');

Route::resource('columns/video-types', 'Columns\VideoTypeController');
Route::resource('columns/strategy', 'Columns\StrategyController');
Route::resource('columns/stores', 'Columns\StoresController');
Route::resource('columns/sla', 'Columns\PriorityController');
Route::resource('columns/campaigns', 'Columns\CampaignController');

app/Store.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    //
}

app/Http/Controllers/Columns/CampaignController.php
<?php

namespace App\Http\Controllers\Columns;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Campaign;
use Auth;

use Session;

class CampaignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $campaigns = Campaign::all();
        return view('columns.campaign.index',compact('campaigns'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'code' => 'required|max:3',
            'description' => 'required',

        ));

        $data = $request->all();
        $campaigns = new Campaign;
        $campaigns->name = $data['name'];
        $campaigns->code = $data['code'];
        $campaigns->description = $data['description'];
        $campaigns->save();

        Session::flash('success', 'Campaign was created successfully!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'description' => 'required',
            'code' => 'required|max:3',
        ));

        $data = $request->all();
        $campaigns = Campaign::find($id);
        $campaigns->name = $data['name'];
        $campaigns->code = $data['code'];
        $campaigns->description = $data['description'];
        $campaigns->save();

        Session::flash('success', 'Campaign was updated successfully!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Columns/PriorityController.php
<?php

namespace App\Http\Controllers\Columns;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Auth;
use Session;

use App\Priority;

class PriorityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == null)
        {
        $priorities = Priority::all();
        return view('columns.sla.index', compact('priorities'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'description' => 'required',
        ));

        $data = $request->all();
        $priorities = new Priority;
        $priorities->name = $data['name'];
        $priorities->description = $data['description'];
        $priorities->save();

        Session::flash('success', 'Priority was created successfully');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'description' => 'required',
        ));

        $data = $request->all();
        $priorities = Priority::find($id);
        $priorities->name = $data['name'];
        $priorities->description = $data['description'];
        $priorities->save();

        Session::flash('success', 'Priority Update was successfully!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Columns/StoresController.php
<?php

namespace App\Http\Controllers\Columns;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Auth;
use Session;

use App\Store;

class StoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == null)
        {
        $stores = Store::all();
        return view('columns.store.index',compact('stores'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'code' => 'required|max:3',
        ));

        $data = $request->all();
        $stores = new Store;
        $stores->name = $data['name'];
        $stores->code = $data['code'];
        $stores->save();

        Session::flash('success', 'Stores Created was successfully!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'code' => 'required|max:3',
        ));

        $data = $request->all();
        $stores = Store::find($id);
        $stores->name = $data['name'];
        $stores->code = $data['code'];
        $stores->save();

        Session::flash('success', 'Stores Updated was successfully!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Columns/StrategyController.php
<?php

namespace App\Http\Controllers\Columns;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Strategy;

use Auth;

use Session;

class StrategyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == null)
        {
        $strategies = Strategy::all();
        return view('columns.strategy.index',compact('strategies'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('columns.strategy.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required',
            'description' => 'required',
        ));

        $data = $request->all();
        $strategies = new Strategy;
        $strategies->name = $data['name'];
        $strategies->description = $data['description'];
        $strategies->save();

        Session::flash('success', 'Strategy was created successfully!');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'description' => 'required',
        ));

        $data = $request->all();
        $strategies = Strategy::find($id);
        $strategies->name = $data['name'];
        $strategies->description = $data['description'];
        $strategies->save();

        Session::flash('success', 'Strategy Update was successfully!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Columns/VideoTypeController.php
<?php

namespace App\Http\Controllers\Columns;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\VideoType;
use Auth;

use Session;

class VideoTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == null)
        {
        $videotypes = VideoType::all();
        return view('columns.video-types.index', compact('videotypes'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('columns.video-types.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'description' => 'required|min:10|max:500',
        ));

        $data = $request->all();
        $videotypes = new VideoType;
        $videotypes->name = $data['name'];
        $videotypes->description = $data['description'];
        $videotypes->save();

        Session::flash('success', 'Video Types Created was successfully!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, array(
            'name' => 'required|max:20',
            'description' => 'required',
        ));

        $data = $request->all();
        $videotypes = VideoType::find($id);
        $videotypes->name = $data['name'];
        $videotypes->description = $data['description'];
        $videotypes->save();

        Session::flash('success', 'Video Types Update was successfully!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/columns/store/index.blade.php
@extends('main')

@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            @if (Session::has('success'))

            <div class="alert alert-success" role="alert">
                <strong>Success:</strong> {{ Session::get('success') }}
            </div>

            @endif

            @if (count($errors) > 0)
            <div class="alert alert-danger" role="alert">
                <strong>Errors:</strong>
                <ul>
                @foreach ($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
                </ul>
            </div>
            @endif
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>All Stores</h1>
                </div>
                <div class="modal fade" id="create-store">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Store</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                            <form method="POST" action="{{ route('stores.store') }}">
                            @csrf
                                <div class="form-group">
                                    <input class="form-control" type="text" id="name" name="name" placeholder="Create New Strategy" required autocomplete="name" style="text-transform: capitalize;" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" type="text" id="code" name="code" placeholder="Code" required autcomplete="code" maxlength="3" style="text-transform: uppercase;">
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <div class="col-xm-6">
                            <ol class="breadcrumb float-sm-right">
                                <button class="btn btn-primary btn-md" data-toggle="modal" data-target="#create-store">Add <i class="fas fa-plus"></i></button>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Code</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($stores as $store)
                            <tr>
                            <td style="text-transform: capitalize;">{{ $store->name }}</td>
                            <td style="text-transform: uppercase;">{{ $store->code }}</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#edit-store-{{$store->id}}">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                    <div class="modal fade" id="edit-store-{{$store->id}}">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Edit Store</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                <form method="POST" action="{{ route('stores.update', $store->id)}}">@csrf
                                                @method('PUT')
                                                    <div class="form-group">
                                                        <input class="form-control" style="text-transform: capitalize;" type="text" id="name" name="name" value="{{$store->name}}">
                                                    </div>
                                                    <div class="form-group">
                                                        <input class="form-control" style="text-transform: uppercase;" type="text" id="code" name="code" value="{{$store->code}}" maxlength="3">
                                                    </div>
                                                </div>
                                                <div class="modal-footer justify-content-between">
                                                    <button type="submit" class="btn btn-primary">Update</button>
                                                </div>
                                            </form>
                                            </div>
                                        </div>
                                    </div>
                                    <button type="button" class="btn btn-default">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                    <button type="button" class="btn btn-default">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>
                            </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>

@endsection